
import 'package:flutter/material.dart';

import 'package:flutter_api_samples/material/about/about_list_tile.0.dart' as about_list_tile_0;
import 'package:flutter_api_samples/material/action_buttons/action_icon_theme.0.dart' as action_icon_theme_0;
import 'package:flutter_api_samples/material/action_chip/action_chip.0.dart' as action_chip_0;
import 'package:flutter_api_samples/material/animated_icon/animated_icon.0.dart' as animated_icon_0;
import 'package:flutter_api_samples/material/animated_icon/animated_icons_data.0.dart' as animated_icons_data_0;
import 'package:flutter_api_samples/material/app_bar/app_bar.0.dart' as app_bar_0;
import 'package:flutter_api_samples/material/app_bar/app_bar.1.dart' as app_bar_1;
import 'package:flutter_api_samples/material/app_bar/app_bar.2.dart' as app_bar_2;
import 'package:flutter_api_samples/material/app_bar/app_bar.3.dart' as app_bar_3;
import 'package:flutter_api_samples/material/app_bar/sliver_app_bar.1.dart' as sliver_app_bar_1;
import 'package:flutter_api_samples/material/app_bar/sliver_app_bar.2.dart' as sliver_app_bar_2;
import 'package:flutter_api_samples/material/app_bar/sliver_app_bar.3.dart' as sliver_app_bar_3;
import 'package:flutter_api_samples/material/app_bar/sliver_app_bar.4.dart' as sliver_app_bar_4;
import 'package:flutter_api_samples/material/autocomplete/autocomplete.0.dart' as autocomplete_0;
import 'package:flutter_api_samples/material/autocomplete/autocomplete.1.dart' as autocomplete_1;
import 'package:flutter_api_samples/material/autocomplete/autocomplete.2.dart' as autocomplete_2;
import 'package:flutter_api_samples/material/autocomplete/autocomplete.3.dart' as autocomplete_3;
import 'package:flutter_api_samples/material/autocomplete/autocomplete.4.dart' as autocomplete_4;
import 'package:flutter_api_samples/material/banner/material_banner.0.dart' as material_banner_0;
import 'package:flutter_api_samples/material/banner/material_banner.1.dart' as material_banner_1;
import 'package:flutter_api_samples/material/bottom_app_bar/bottom_app_bar.1.dart' as bottom_app_bar_1;
import 'package:flutter_api_samples/material/bottom_app_bar/bottom_app_bar.2.dart' as bottom_app_bar_2;
import 'package:flutter_api_samples/material/bottom_navigation_bar/bottom_navigation_bar.0.dart' as bottom_navigation_bar_0;
import 'package:flutter_api_samples/material/bottom_navigation_bar/bottom_navigation_bar.1.dart' as bottom_navigation_bar_1;
import 'package:flutter_api_samples/material/bottom_navigation_bar/bottom_navigation_bar.2.dart' as bottom_navigation_bar_2;
import 'package:flutter_api_samples/material/bottom_sheet/show_modal_bottom_sheet.0.dart' as show_modal_bottom_sheet_0;
import 'package:flutter_api_samples/material/bottom_sheet/show_modal_bottom_sheet.1.dart' as show_modal_bottom_sheet_1;
import 'package:flutter_api_samples/material/button_style/button_style.0.dart' as button_style_0;
import 'package:flutter_api_samples/material/card/card.0.dart' as card_0;
import 'package:flutter_api_samples/material/card/card.1.dart' as card_1;
import 'package:flutter_api_samples/material/card/card.2.dart' as card_2;
import 'package:flutter_api_samples/material/checkbox/checkbox.0.dart' as checkbox_0;
import 'package:flutter_api_samples/material/checkbox/checkbox.1.dart' as checkbox_1;
import 'package:flutter_api_samples/material/checkbox_list_tile/checkbox_list_tile.0.dart' as checkbox_list_tile_0;
import 'package:flutter_api_samples/material/checkbox_list_tile/checkbox_list_tile.1.dart' as checkbox_list_tile_1;
import 'package:flutter_api_samples/material/checkbox_list_tile/custom_labeled_checkbox.0.dart' as custom_labeled_checkbox_0;
import 'package:flutter_api_samples/material/checkbox_list_tile/custom_labeled_checkbox.1.dart' as custom_labeled_checkbox_1;
import 'package:flutter_api_samples/material/chip/deletable_chip_attributes.on_deleted.0.dart' as deletable_chip_attributes_on_deleted_0;
import 'package:flutter_api_samples/material/choice_chip/choice_chip.0.dart' as choice_chip_0;
import 'package:flutter_api_samples/material/color_scheme/dynamic_content_color.0.dart' as dynamic_content_color_0;
import 'package:flutter_api_samples/material/context_menu/context_menu_controller.0.dart' as context_menu_controller_0;
import 'package:flutter_api_samples/material/context_menu/editable_text_toolbar_builder.0.dart' as editable_text_toolbar_builder_0;
import 'package:flutter_api_samples/material/context_menu/editable_text_toolbar_builder.1.dart' as editable_text_toolbar_builder_1;
import 'package:flutter_api_samples/material/context_menu/editable_text_toolbar_builder.2.dart' as editable_text_toolbar_builder_2;
import 'package:flutter_api_samples/material/context_menu/selectable_region_toolbar_builder.0.dart' as selectable_region_toolbar_builder_0;
import 'package:flutter_api_samples/material/data_table/data_table.0.dart' as data_table_0;
import 'package:flutter_api_samples/material/data_table/data_table.1.dart' as data_table_1;
import 'package:flutter_api_samples/material/date_picker/show_date_picker.0.dart' as show_date_picker_0;
import 'package:flutter_api_samples/material/date_picker/show_date_range_picker.0.dart' as show_date_range_picker_0;
import 'package:flutter_api_samples/material/dialog/adaptive_alert_dialog.0.dart' as adaptive_alert_dialog_0;
import 'package:flutter_api_samples/material/dialog/alert_dialog.0.dart' as alert_dialog_0;
import 'package:flutter_api_samples/material/dialog/alert_dialog.1.dart' as alert_dialog_1;
import 'package:flutter_api_samples/material/dialog/dialog.0.dart' as dialog_0;
import 'package:flutter_api_samples/material/dialog/show_dialog.0.dart' as show_dialog_0;
import 'package:flutter_api_samples/material/dialog/show_dialog.1.dart' as show_dialog_1;
import 'package:flutter_api_samples/material/dialog/show_dialog.2.dart' as show_dialog_2;
import 'package:flutter_api_samples/material/divider/divider.0.dart' as divider_0;
import 'package:flutter_api_samples/material/divider/divider.1.dart' as divider_1;
import 'package:flutter_api_samples/material/divider/vertical_divider.0.dart' as vertical_divider_0;
import 'package:flutter_api_samples/material/divider/vertical_divider.1.dart' as vertical_divider_1;
import 'package:flutter_api_samples/material/drawer/drawer.0.dart' as drawer_0;
import 'package:flutter_api_samples/material/dropdown/dropdown_button.0.dart' as dropdown_button_0;
import 'package:flutter_api_samples/material/dropdown/dropdown_button.selected_item_builder.0.dart' as dropdown_button_selected_item_builder_0;
import 'package:flutter_api_samples/material/dropdown/dropdown_button.style.0.dart' as dropdown_button_style_0;
import 'package:flutter_api_samples/material/dropdown_menu/dropdown_menu.0.dart' as dropdown_menu_0;
import 'package:flutter_api_samples/material/dropdown_menu/dropdown_menu.1.dart' as dropdown_menu_1;
import 'package:flutter_api_samples/material/dropdown_menu/dropdown_menu_entry_label_widget.0.dart' as dropdown_menu_entry_label_widget_0;
import 'package:flutter_api_samples/material/elevated_button/elevated_button.0.dart' as elevated_button_0;
import 'package:flutter_api_samples/material/expansion_panel/expansion_panel_list.0.dart' as expansion_panel_list_0;
import 'package:flutter_api_samples/material/expansion_panel/expansion_panel_list.expansion_panel_list_radio.0.dart' as expansion_panel_list_expansion_panel_list_radio_0;
import 'package:flutter_api_samples/material/expansion_tile/expansion_tile.0.dart' as expansion_tile_0;
import 'package:flutter_api_samples/material/expansion_tile/expansion_tile.1.dart' as expansion_tile_1;
import 'package:flutter_api_samples/material/filled_button/filled_button.0.dart' as filled_button_0;
import 'package:flutter_api_samples/material/filter_chip/filter_chip.0.dart' as filter_chip_0;
import 'package:flutter_api_samples/material/flexible_space_bar/flexible_space_bar.0.dart' as flexible_space_bar_0;
import 'package:flutter_api_samples/material/floating_action_button/floating_action_button.0.dart' as floating_action_button_0;
import 'package:flutter_api_samples/material/floating_action_button/floating_action_button.1.dart' as floating_action_button_1;
import 'package:flutter_api_samples/material/floating_action_button/floating_action_button.2.dart' as floating_action_button_2;
import 'package:flutter_api_samples/material/floating_action_button_location/standard_fab_location.0.dart' as standard_fab_location_0;
import 'package:flutter_api_samples/material/icon_button/icon_button.0.dart' as icon_button_0;
import 'package:flutter_api_samples/material/icon_button/icon_button.1.dart' as icon_button_1;
import 'package:flutter_api_samples/material/icon_button/icon_button.2.dart' as icon_button_2;
import 'package:flutter_api_samples/material/icon_button/icon_button.3.dart' as icon_button_3;
import 'package:flutter_api_samples/material/ink/ink.image_clip.0.dart' as ink_image_clip_0;
import 'package:flutter_api_samples/material/ink/ink.image_clip.1.dart' as ink_image_clip_1;
import 'package:flutter_api_samples/material/ink_well/ink_well.0.dart' as ink_well_0;
import 'package:flutter_api_samples/material/input_chip/input_chip.0.dart' as input_chip_0;
import 'package:flutter_api_samples/material/input_chip/input_chip.1.dart' as input_chip_1;
import 'package:flutter_api_samples/material/input_decorator/input_decoration.0.dart' as input_decoration_0;
import 'package:flutter_api_samples/material/input_decorator/input_decoration.1.dart' as input_decoration_1;
import 'package:flutter_api_samples/material/input_decorator/input_decoration.2.dart' as input_decoration_2;
import 'package:flutter_api_samples/material/input_decorator/input_decoration.3.dart' as input_decoration_3;
import 'package:flutter_api_samples/material/input_decorator/input_decoration.floating_label_style_error.0.dart' as input_decoration_floating_label_style_error_0;
import 'package:flutter_api_samples/material/input_decorator/input_decoration.label.0.dart' as input_decoration_label_0;
import 'package:flutter_api_samples/material/input_decorator/input_decoration.label_style_error.0.dart' as input_decoration_label_style_error_0;
import 'package:flutter_api_samples/material/input_decorator/input_decoration.material_state.0.dart' as input_decoration_material_state_0;
import 'package:flutter_api_samples/material/input_decorator/input_decoration.material_state.1.dart' as input_decoration_material_state_1;
import 'package:flutter_api_samples/material/input_decorator/input_decoration.prefix_icon.0.dart' as input_decoration_prefix_icon_0;
import 'package:flutter_api_samples/material/input_decorator/input_decoration.prefix_icon_constraints.0.dart' as input_decoration_prefix_icon_constraints_0;
import 'package:flutter_api_samples/material/input_decorator/input_decoration.suffix_icon.0.dart' as input_decoration_suffix_icon_0;
import 'package:flutter_api_samples/material/input_decorator/input_decoration.suffix_icon_constraints.0.dart' as input_decoration_suffix_icon_constraints_0;
import 'package:flutter_api_samples/material/list_tile/custom_list_item.0.dart' as custom_list_item_0;
import 'package:flutter_api_samples/material/list_tile/custom_list_item.1.dart' as custom_list_item_1;
import 'package:flutter_api_samples/material/list_tile/list_tile.0.dart' as list_tile_0;
import 'package:flutter_api_samples/material/list_tile/list_tile.1.dart' as list_tile_1;
import 'package:flutter_api_samples/material/list_tile/list_tile.2.dart' as list_tile_2;
import 'package:flutter_api_samples/material/list_tile/list_tile.3.dart' as list_tile_3;
import 'package:flutter_api_samples/material/list_tile/list_tile.4.dart' as list_tile_4;
import 'package:flutter_api_samples/material/list_tile/list_tile.selected.0.dart' as list_tile_selected_0;
import 'package:flutter_api_samples/material/material_state/material_state_border_side.0.dart' as material_state_border_side_0;
import 'package:flutter_api_samples/material/material_state/material_state_mouse_cursor.0.dart' as material_state_mouse_cursor_0;
import 'package:flutter_api_samples/material/material_state/material_state_outlined_border.0.dart' as material_state_outlined_border_0;
import 'package:flutter_api_samples/material/material_state/material_state_property.0.dart' as material_state_property_0;
import 'package:flutter_api_samples/material/menu_anchor/checkbox_menu_button.0.dart' as checkbox_menu_button_0;
import 'package:flutter_api_samples/material/menu_anchor/menu_accelerator_label.0.dart' as menu_accelerator_label_0;
import 'package:flutter_api_samples/material/menu_anchor/menu_anchor.0.dart' as menu_anchor_0;
import 'package:flutter_api_samples/material/menu_anchor/menu_anchor.1.dart' as menu_anchor_1;
import 'package:flutter_api_samples/material/menu_anchor/menu_anchor.2.dart' as menu_anchor_2;
import 'package:flutter_api_samples/material/menu_anchor/menu_bar.0.dart' as menu_bar_0;
import 'package:flutter_api_samples/material/menu_anchor/radio_menu_button.0.dart' as radio_menu_button_0;
import 'package:flutter_api_samples/material/navigation_bar/navigation_bar.0.dart' as navigation_bar_0;
import 'package:flutter_api_samples/material/navigation_bar/navigation_bar.1.dart' as navigation_bar_1;
import 'package:flutter_api_samples/material/navigation_bar/navigation_bar.2.dart' as navigation_bar_2;
import 'package:flutter_api_samples/material/navigation_drawer/navigation_drawer.0.dart' as navigation_drawer_0;
import 'package:flutter_api_samples/material/navigation_rail/navigation_rail.0.dart' as navigation_rail_0;
import 'package:flutter_api_samples/material/navigation_rail/navigation_rail.1.dart' as navigation_rail_1;
import 'package:flutter_api_samples/material/navigation_rail/navigation_rail.extended_animation.0.dart' as navigation_rail_extended_animation_0;
import 'package:flutter_api_samples/material/outlined_button/outlined_button.0.dart' as outlined_button_0;
import 'package:flutter_api_samples/material/page_transitions_theme/page_transitions_theme.0.dart' as page_transitions_theme_0;
import 'package:flutter_api_samples/material/page_transitions_theme/page_transitions_theme.1.dart' as page_transitions_theme_1;
import 'package:flutter_api_samples/material/paginated_data_table/paginated_data_table.0.dart' as paginated_data_table_0;
import 'package:flutter_api_samples/material/paginated_data_table/paginated_data_table.1.dart' as paginated_data_table_1;
import 'package:flutter_api_samples/material/platform_menu_bar/platform_menu_bar.0.dart' as platform_menu_bar_0;
import 'package:flutter_api_samples/material/popup_menu/popup_menu.0.dart' as popup_menu_0;
import 'package:flutter_api_samples/material/popup_menu/popup_menu.1.dart' as popup_menu_1;
import 'package:flutter_api_samples/material/progress_indicator/circular_progress_indicator.0.dart' as circular_progress_indicator_0;
import 'package:flutter_api_samples/material/progress_indicator/circular_progress_indicator.1.dart' as circular_progress_indicator_1;
import 'package:flutter_api_samples/material/progress_indicator/linear_progress_indicator.0.dart' as linear_progress_indicator_0;
import 'package:flutter_api_samples/material/progress_indicator/linear_progress_indicator.1.dart' as linear_progress_indicator_1;
import 'package:flutter_api_samples/material/radio/radio.0.dart' as radio_0;
import 'package:flutter_api_samples/material/radio/radio.toggleable.0.dart' as radio_toggleable_0;
import 'package:flutter_api_samples/material/radio_list_tile/custom_labeled_radio.0.dart' as custom_labeled_radio_0;
import 'package:flutter_api_samples/material/radio_list_tile/custom_labeled_radio.1.dart' as custom_labeled_radio_1;
import 'package:flutter_api_samples/material/radio_list_tile/radio_list_tile.0.dart' as radio_list_tile_0;
import 'package:flutter_api_samples/material/radio_list_tile/radio_list_tile.1.dart' as radio_list_tile_1;
import 'package:flutter_api_samples/material/radio_list_tile/radio_list_tile.toggleable.0.dart' as radio_list_tile_toggleable_0;
import 'package:flutter_api_samples/material/range_slider/range_slider.0.dart' as range_slider_0;
import 'package:flutter_api_samples/material/refresh_indicator/refresh_indicator.0.dart' as refresh_indicator_0;
import 'package:flutter_api_samples/material/refresh_indicator/refresh_indicator.1.dart' as refresh_indicator_1;
import 'package:flutter_api_samples/material/reorderable_list/reorderable_list_view.0.dart' as reorderable_list_view_0;
import 'package:flutter_api_samples/material/reorderable_list/reorderable_list_view.1.dart' as reorderable_list_view_1;
import 'package:flutter_api_samples/material/reorderable_list/reorderable_list_view.2.dart' as reorderable_list_view_2;
import 'package:flutter_api_samples/material/reorderable_list/reorderable_list_view.build_default_drag_handles.0.dart' as reorderable_list_view_build_default_drag_handles_0;
import 'package:flutter_api_samples/material/reorderable_list/reorderable_list_view.reorderable_list_view_builder.0.dart' as reorderable_list_view_reorderable_list_view_builder_0;
import 'package:flutter_api_samples/material/scaffold/scaffold.0.dart' as scaffold_0;
import 'package:flutter_api_samples/material/scaffold/scaffold.1.dart' as scaffold_1;
import 'package:flutter_api_samples/material/scaffold/scaffold.2.dart' as scaffold_2;
import 'package:flutter_api_samples/material/scaffold/scaffold.drawer.0.dart' as scaffold_drawer_0;
import 'package:flutter_api_samples/material/scaffold/scaffold.end_drawer.0.dart' as scaffold_end_drawer_0;
import 'package:flutter_api_samples/material/scaffold/scaffold.of.0.dart' as scaffold_of_0;
import 'package:flutter_api_samples/material/scaffold/scaffold.of.1.dart' as scaffold_of_1;
import 'package:flutter_api_samples/material/scaffold/scaffold_messenger.0.dart' as scaffold_messenger_0;
import 'package:flutter_api_samples/material/scaffold/scaffold_messenger.of.0.dart' as scaffold_messenger_of_0;
import 'package:flutter_api_samples/material/scaffold/scaffold_messenger.of.1.dart' as scaffold_messenger_of_1;
import 'package:flutter_api_samples/material/scaffold/scaffold_messenger_state.show_material_banner.0.dart' as scaffold_messenger_state_show_material_banner_0;
import 'package:flutter_api_samples/material/scaffold/scaffold_messenger_state.show_snack_bar.0.dart' as scaffold_messenger_state_show_snack_bar_0;
import 'package:flutter_api_samples/material/scaffold/scaffold_messenger_state.show_snack_bar.1.dart' as scaffold_messenger_state_show_snack_bar_1;
import 'package:flutter_api_samples/material/scaffold/scaffold_state.show_bottom_sheet.0.dart' as scaffold_state_show_bottom_sheet_0;
import 'package:flutter_api_samples/material/scrollbar/scrollbar.0.dart' as scrollbar_0;
import 'package:flutter_api_samples/material/scrollbar/scrollbar.1.dart' as scrollbar_1;
import 'package:flutter_api_samples/material/search_anchor/search_anchor.0.dart' as search_anchor_0;
import 'package:flutter_api_samples/material/search_anchor/search_anchor.1.dart' as search_anchor_1;
import 'package:flutter_api_samples/material/search_anchor/search_anchor.2.dart' as search_anchor_2;
import 'package:flutter_api_samples/material/search_anchor/search_anchor.3.dart' as search_anchor_3;
import 'package:flutter_api_samples/material/search_anchor/search_anchor.4.dart' as search_anchor_4;
import 'package:flutter_api_samples/material/search_anchor/search_bar.0.dart' as search_bar_0;
import 'package:flutter_api_samples/material/segmented_button/segmented_button.0.dart' as segmented_button_0;
import 'package:flutter_api_samples/material/selectable_region/selectable_region.0.dart' as selectable_region_0;
import 'package:flutter_api_samples/material/selection_area/selection_area.0.dart' as selection_area_0;
import 'package:flutter_api_samples/material/selection_container/selection_container.0.dart' as selection_container_0;
import 'package:flutter_api_samples/material/selection_container/selection_container_disabled.0.dart' as selection_container_disabled_0;
import 'package:flutter_api_samples/material/slider/slider.0.dart' as slider_0;
import 'package:flutter_api_samples/material/slider/slider.1.dart' as slider_1;
import 'package:flutter_api_samples/material/slider/slider.2.dart' as slider_2;
import 'package:flutter_api_samples/material/snack_bar/snack_bar.0.dart' as snack_bar_0;
import 'package:flutter_api_samples/material/snack_bar/snack_bar.1.dart' as snack_bar_1;
import 'package:flutter_api_samples/material/snack_bar/snack_bar.2.dart' as snack_bar_2;
import 'package:flutter_api_samples/material/stepper/stepper.0.dart' as stepper_0;
import 'package:flutter_api_samples/material/stepper/stepper.controls_builder.0.dart' as stepper_controls_builder_0;
import 'package:flutter_api_samples/material/switch/switch.0.dart' as switch_0;
import 'package:flutter_api_samples/material/switch/switch.1.dart' as switch_1;
import 'package:flutter_api_samples/material/switch/switch.2.dart' as switch_2;
import 'package:flutter_api_samples/material/switch/switch.3.dart' as switch_3;
import 'package:flutter_api_samples/material/switch_list_tile/custom_labeled_switch.0.dart' as custom_labeled_switch_0;
import 'package:flutter_api_samples/material/switch_list_tile/custom_labeled_switch.1.dart' as custom_labeled_switch_1;
import 'package:flutter_api_samples/material/switch_list_tile/switch_list_tile.0.dart' as switch_list_tile_0;
import 'package:flutter_api_samples/material/switch_list_tile/switch_list_tile.1.dart' as switch_list_tile_1;
import 'package:flutter_api_samples/material/tab_controller/tab_controller.1.dart' as tab_controller_1;
import 'package:flutter_api_samples/material/tabs/tab_bar.0.dart' as tab_bar_0;
import 'package:flutter_api_samples/material/tabs/tab_bar.1.dart' as tab_bar_1;
import 'package:flutter_api_samples/material/tabs/tab_bar.2.dart' as tab_bar_2;
import 'package:flutter_api_samples/material/text_button/text_button.0.dart' as text_button_0;
import 'package:flutter_api_samples/material/text_button/text_button.1.dart' as text_button_1;
import 'package:flutter_api_samples/material/text_field/text_field.0.dart' as text_field_0;
import 'package:flutter_api_samples/material/text_field/text_field.1.dart' as text_field_1;
import 'package:flutter_api_samples/material/text_field/text_field.2.dart' as text_field_2;
import 'package:flutter_api_samples/material/text_form_field/text_form_field.1.dart' as text_form_field_1;
import 'package:flutter_api_samples/material/theme/theme_extension.1.dart' as theme_extension_1;
import 'package:flutter_api_samples/material/theme_data/theme_data.0.dart' as theme_data_0;
import 'package:flutter_api_samples/material/time_picker/show_time_picker.0.dart' as show_time_picker_0;
import 'package:flutter_api_samples/material/toggle_buttons/toggle_buttons.0.dart' as toggle_buttons_0;
import 'package:flutter_api_samples/material/toggle_buttons/toggle_buttons.1.dart' as toggle_buttons_1;
import 'package:flutter_api_samples/material/tooltip/tooltip.0.dart' as tooltip_0;
import 'package:flutter_api_samples/material/tooltip/tooltip.1.dart' as tooltip_1;
import 'package:flutter_api_samples/material/tooltip/tooltip.2.dart' as tooltip_2;
import 'package:flutter_api_samples/material/tooltip/tooltip.3.dart' as tooltip_3;


Map<String, WidgetBuilder> routesMap = {
'about_list_tile_0':(context) => const about_list_tile_0.AboutListTileExampleApp(),
'action_icon_theme_0':(context) => const action_icon_theme_0.ActionIconThemeExampleApp(),
'action_chip_0':(context) => const action_chip_0.ChipApp(),
'animated_icon_0':(context) => const animated_icon_0.AnimatedIconApp(),
'animated_icons_data_0':(context) => const animated_icons_data_0.AnimatedIconApp(),
'app_bar_0':(context) => const app_bar_0.AppBarApp(),
'app_bar_1':(context) => const app_bar_1.AppBarApp(),
'app_bar_2':(context) => const app_bar_2.AppBarApp(),
'app_bar_3':(context) => const app_bar_3.AppBarApp(),
'sliver_app_bar_1':(context) => const sliver_app_bar_1.AppBarApp(),
'sliver_app_bar_2':(context) => const sliver_app_bar_2.AppBarMediumApp(),
'sliver_app_bar_3':(context) => const sliver_app_bar_3.AppBarLargeApp(),
'sliver_app_bar_4':(context) => const sliver_app_bar_4.StretchableSliverAppBar(),
'autocomplete_0':(context) => const autocomplete_0.AutocompleteExampleApp(),
'autocomplete_1':(context) => const autocomplete_1.AutocompleteExampleApp(),
'autocomplete_2':(context) => const autocomplete_2.AutocompleteExampleApp(),
'autocomplete_3':(context) => const autocomplete_3.AutocompleteExampleApp(),
'autocomplete_4':(context) => const autocomplete_4.AutocompleteExampleApp(),
'material_banner_0':(context) => const material_banner_0.MaterialBannerExampleApp(),
'material_banner_1':(context) => const material_banner_1.MaterialBannerExampleApp(),
'bottom_app_bar_1':(context) => const  bottom_app_bar_1.BottomAppBarDemo(),
'bottom_app_bar_2':(context) => const  bottom_app_bar_2.BottomAppBarDemo(),
'bottom_navigation_bar_0':(context) => const bottom_navigation_bar_0.BottomNavigationBarExampleApp(),
'bottom_navigation_bar_1':(context) => const bottom_navigation_bar_1.BottomNavigationBarExampleApp(),
'bottom_navigation_bar_2':(context) => const bottom_navigation_bar_2.BottomNavigationBarExampleApp(),
'show_modal_bottom_sheet_0':(context) => const show_modal_bottom_sheet_0.BottomSheetApp(),
'show_modal_bottom_sheet_1':(context) => const show_modal_bottom_sheet_1.BottomSheetApp(),
'button_style_0':(context) => const button_style_0.ButtonApp(),
'card_0':(context) => const card_0.CardExampleApp(),
'card_1':(context) => const card_1.CardExampleApp(),
'card_2':(context) => const card_2.CardExamplesApp(),
'checkbox_0':(context) => const checkbox_0.CheckboxExampleApp(),
'checkbox_1':(context) => const checkbox_1.CheckboxExampleApp(),
'checkbox_list_tile_0':(context) => const checkbox_list_tile_0.CheckboxListTileApp(),
'checkbox_list_tile_1':(context) => const checkbox_list_tile_1.CheckboxListTileApp(),
'custom_labeled_checkbox_0':(context) => const custom_labeled_checkbox_0.LabeledCheckboxApp(),
'custom_labeled_checkbox_1':(context) => const custom_labeled_checkbox_1.LabeledCheckboxApp(),
'deletable_chip_attributes_on_deleted_0':(context) => const deletable_chip_attributes_on_deleted_0.OnDeletedExampleApp(),
'choice_chip_0':(context) => const choice_chip_0.ChipApp(),
'dynamic_content_color_0':(context) =>  dynamic_content_color_0.DynamicColorExample(),
'context_menu_controller_0':(context) => const context_menu_controller_0.ContextMenuControllerExampleApp(),
'editable_text_toolbar_builder_0':(context) => const editable_text_toolbar_builder_0.EditableTextToolbarBuilderExampleApp(),
'editable_text_toolbar_builder_1':(context) => const editable_text_toolbar_builder_1.EditableTextToolbarBuilderExampleApp(),
'editable_text_toolbar_builder_2':(context) => const editable_text_toolbar_builder_2.EditableTextToolbarBuilderExampleApp(),
'selectable_region_toolbar_builder_0':(context) => const selectable_region_toolbar_builder_0.SelectableRegionToolbarBuilderExampleApp(),
'data_table_0':(context) => const data_table_0.DataTableExampleApp(),
'data_table_1':(context) => const data_table_1.DataTableExampleApp(),
'show_date_picker_0':(context) => const show_date_picker_0.DatePickerApp(),
'show_date_range_picker_0':(context) => const show_date_range_picker_0.DatePickerApp(),
'adaptive_alert_dialog_0':(context) => const adaptive_alert_dialog_0.AdaptiveAlertDialogApp(),
'alert_dialog_0':(context) => const alert_dialog_0.AlertDialogExampleApp(),
'alert_dialog_1':(context) => const alert_dialog_1.AlertDialogExampleApp(),
'dialog_0':(context) => const dialog_0.DialogExampleApp(),
'show_dialog_0':(context) => const show_dialog_0.ShowDialogExampleApp(),
'show_dialog_1':(context) => const show_dialog_1.ShowDialogExampleApp(),
'show_dialog_2':(context) => const show_dialog_2.ShowDialogExampleApp(),
'divider_0':(context) => const divider_0.DividerExampleApp(),
'divider_1':(context) => const divider_1.DividerExampleApp(),
'vertical_divider_0':(context) => const vertical_divider_0.VerticalDividerExampleApp(),
'vertical_divider_1':(context) => const vertical_divider_1.VerticalDividerExampleApp(),
'drawer_0':(context) => const drawer_0.DrawerApp(),
'dropdown_button_0':(context) => const dropdown_button_0.DropdownButtonApp(),
'dropdown_button_selected_item_builder_0':(context) => const dropdown_button_selected_item_builder_0.DropdownButtonApp(),
'dropdown_button_style_0':(context) => const dropdown_button_style_0.DropdownButtonApp(),
'dropdown_menu_0':(context) => const dropdown_menu_0.DropdownMenuExample(),
'dropdown_menu_1':(context) => const dropdown_menu_1.DropdownMenuApp(),
'dropdown_menu_entry_label_widget_0':(context) => const dropdown_menu_entry_label_widget_0.DropdownMenuEntryLabelWidgetExampleApp(),
'elevated_button_0':(context) => const elevated_button_0.ElevatedButtonExampleApp(),
'expansion_panel_list_0':(context) => const expansion_panel_list_0.ExpansionPanelListExampleApp(),
'expansion_panel_list_expansion_panel_list_radio_0':(context) => const expansion_panel_list_expansion_panel_list_radio_0.ExpansionPanelListRadioExampleApp(),
'expansion_tile_0':(context) => const expansion_tile_0.ExpansionTileApp(),
'expansion_tile_1':(context) => const expansion_tile_1.ExpansionTileControllerApp(),
'filled_button_0':(context) => const filled_button_0.FilledButtonApp(),
'filter_chip_0':(context) => const filter_chip_0.ChipApp(),
'flexible_space_bar_0':(context) => const flexible_space_bar_0.FlexibleSpaceBarExampleApp(),
'floating_action_button_0':(context) => const floating_action_button_0.FloatingActionButtonExampleApp(),
'floating_action_button_1':(context) => const floating_action_button_1.FloatingActionButtonExampleApp(),
'floating_action_button_2':(context) => const floating_action_button_2.FloatingActionButtonExampleApp(),
'standard_fab_location_0':(context) => const standard_fab_location_0.StandardFabLocationExampleApp(),
'icon_button_0':(context) => const icon_button_0.IconButtonExampleApp(),
'icon_button_1':(context) => const icon_button_1.IconButtonExampleApp(),
'icon_button_2':(context) => const icon_button_2.IconButtonApp(),
'icon_button_3':(context) => const icon_button_3.IconButtonToggleApp(),
'ink_image_clip_0':(context) => const ink_image_clip_0.MyApp(),
'ink_image_clip_1':(context) => const ink_image_clip_1.MyApp(),
'ink_well_0':(context) => const ink_well_0.InkWellExampleApp(),
'input_chip_0':(context) => const input_chip_0.ChipApp(),
'input_chip_1':(context) => const input_chip_1.EditableChipFieldApp(),
'input_decoration_0':(context) => const input_decoration_0.InputDecorationExampleApp(),
'input_decoration_1':(context) => const input_decoration_1.InputDecorationExampleApp(),
'input_decoration_2':(context) => const input_decoration_2.InputDecorationExampleApp(),
'input_decoration_3':(context) => const input_decoration_3.InputDecorationExampleApp(),
'input_decoration_floating_label_style_error_0':(context) => const input_decoration_floating_label_style_error_0.FloatingLabelStyleErrorExampleApp(),
'input_decoration_label_0':(context) => const input_decoration_label_0.LabelExampleApp(),
'input_decoration_label_style_error_0':(context) => const input_decoration_label_style_error_0.LabelStyleErrorExampleApp(),
'input_decoration_material_state_0':(context) => const input_decoration_material_state_0.MaterialStateExampleApp(),
'input_decoration_material_state_1':(context) => const input_decoration_material_state_1.MaterialStateExampleApp(),
'input_decoration_prefix_icon_0':(context) => const input_decoration_prefix_icon_0.PrefixIconExampleApp(),
'input_decoration_prefix_icon_constraints_0':(context) => const input_decoration_prefix_icon_constraints_0.PrefixIconConstraintsExampleApp(),
'input_decoration_suffix_icon_0':(context) => const input_decoration_suffix_icon_0.SuffixIconExampleApp(),
'input_decoration_suffix_icon_constraints_0':(context) => const input_decoration_suffix_icon_constraints_0.SuffixIconConstraintsExampleApp(),
'custom_list_item_0':(context) => const custom_list_item_0.CustomListItemApp(),
'custom_list_item_1':(context) => const custom_list_item_1.CustomListItemApp(),
'list_tile_0':(context) => const list_tile_0.ListTileApp(),
'list_tile_1':(context) => const list_tile_1.ListTileApp(),
'list_tile_2':(context) => const list_tile_2.ListTileApp(),
'list_tile_3':(context) => const list_tile_3.ListTileApp(),
'list_tile_4':(context) => const list_tile_4.ListTileApp(),
'list_tile_selected_0':(context) => const list_tile_selected_0.ListTileApp(),
'material_state_border_side_0':(context) => const material_state_border_side_0.MaterialStateBorderSideExampleApp(),
'material_state_mouse_cursor_0':(context) => const material_state_mouse_cursor_0.MaterialStateMouseCursorExampleApp(),
'material_state_outlined_border_0':(context) => const material_state_outlined_border_0.MaterialStateOutlinedBorderExampleApp(),
'material_state_property_0':(context) => const material_state_property_0.MaterialStatePropertyExampleApp(),
'checkbox_menu_button_0':(context) => const checkbox_menu_button_0.MenuApp(),
'menu_accelerator_label_0':(context) => const menu_accelerator_label_0.MenuAcceleratorApp(),
'menu_anchor_0':(context) => const menu_anchor_0.MenuApp(),
'menu_anchor_1':(context) => const menu_anchor_1.ContextMenuApp(),
'menu_anchor_2':(context) => const menu_anchor_2.MenuAnchorApp(),
'menu_bar_0':(context) => const menu_bar_0.MenuBarApp(),
'radio_menu_button_0':(context) => const radio_menu_button_0.MenuApp(),
'navigation_bar_0':(context) => const navigation_bar_0.NavigationBarApp(),
'navigation_bar_1':(context) => const navigation_bar_1.NavigationBarApp(),
'navigation_bar_2':(context) => const navigation_bar_2.Home(),
'navigation_drawer_0':(context) => const navigation_drawer_0.NavigationDrawerApp(),
'navigation_rail_0':(context) => const navigation_rail_0.NavigationRailExampleApp(),
'navigation_rail_1':(context) => const navigation_rail_1.NavigationRailExampleApp(),
'navigation_rail_extended_animation_0':(context) => const navigation_rail_extended_animation_0.ExtendedAnimationExampleApp(),
'outlined_button_0':(context) => const outlined_button_0.OutlinedButtonExampleApp(),
'page_transitions_theme_0':(context) => const page_transitions_theme_0.PageTransitionsThemeApp(),
'page_transitions_theme_1':(context) => const page_transitions_theme_1.PageTransitionsThemeApp(),
'paginated_data_table_0':(context) => const paginated_data_table_0.DataTableExampleApp(),
'paginated_data_table_1':(context) => const paginated_data_table_1.DataTableExampleApp(),
'platform_menu_bar_0':(context) => const platform_menu_bar_0.ExampleApp(),
'popup_menu_0':(context) => const popup_menu_0.PopupMenuApp(),
'popup_menu_1':(context) => const popup_menu_1.PopupMenuApp(),
'circular_progress_indicator_0':(context) => const circular_progress_indicator_0.ProgressIndicatorApp(),
'circular_progress_indicator_1':(context) => const circular_progress_indicator_1.ProgressIndicatorApp(),
'linear_progress_indicator_0':(context) => const linear_progress_indicator_0.ProgressIndicatorApp(),
'linear_progress_indicator_1':(context) => const linear_progress_indicator_1.ProgressIndicatorApp(),
'radio_0':(context) => const radio_0.RadioExampleApp(),
'radio_toggleable_0':(context) => const radio_toggleable_0.ToggleableExampleApp(),
'custom_labeled_radio_0':(context) => const custom_labeled_radio_0.LabeledRadioApp(),
'custom_labeled_radio_1':(context) => const custom_labeled_radio_1.LabeledRadioApp(),
'radio_list_tile_0':(context) => const radio_list_tile_0.RadioListTileApp(),
'radio_list_tile_1':(context) => const radio_list_tile_1.RadioListTileApp(),
'radio_list_tile_toggleable_0':(context) => const radio_list_tile_toggleable_0.RadioListTileApp(),
'range_slider_0':(context) => const range_slider_0.RangeSliderExampleApp(),
'refresh_indicator_0':(context) => const refresh_indicator_0.RefreshIndicatorExampleApp(),
'refresh_indicator_1':(context) => const refresh_indicator_1.RefreshIndicatorExampleApp(),
'reorderable_list_view_0':(context) => const reorderable_list_view_0.ReorderableApp(),
'reorderable_list_view_1':(context) => const reorderable_list_view_1.ReorderableApp(),
'reorderable_list_view_2':(context) => const reorderable_list_view_2.ReorderableApp(),
'reorderable_list_view_build_default_drag_handles_0':(context) => const reorderable_list_view_build_default_drag_handles_0.ReorderableApp(),
'reorderable_list_view_reorderable_list_view_builder_0':(context) => const reorderable_list_view_reorderable_list_view_builder_0.ReorderableApp(),
'scaffold_0':(context) => const scaffold_0.ScaffoldExampleApp(),
'scaffold_1':(context) => const scaffold_1.ScaffoldExampleApp(),
'scaffold_2':(context) => const scaffold_2.ScaffoldExampleApp(),
'scaffold_drawer_0':(context) => const scaffold_drawer_0.DrawerExampleApp(),
'scaffold_end_drawer_0':(context) => const scaffold_end_drawer_0.EndDrawerExampleApp(),
'scaffold_of_0':(context) => const scaffold_of_0.OfExampleApp(),
'scaffold_of_1':(context) => const scaffold_of_1.OfExampleApp(),
'scaffold_messenger_0':(context) => const scaffold_messenger_0.ScaffoldMessengerExampleApp(),
'scaffold_messenger_of_0':(context) => const scaffold_messenger_of_0.OfExampleApp(),
'scaffold_messenger_of_1':(context) => const scaffold_messenger_of_1.OfExampleApp(),
'scaffold_messenger_state_show_material_banner_0':(context) => const scaffold_messenger_state_show_material_banner_0.ShowMaterialBannerExampleApp(),
'scaffold_messenger_state_show_snack_bar_0':(context) => const scaffold_messenger_state_show_snack_bar_0.ShowSnackBarExampleApp(),
'scaffold_messenger_state_show_snack_bar_1':(context) => const scaffold_messenger_state_show_snack_bar_1.SnackBarApp(),
'scaffold_state_show_bottom_sheet_0':(context) => const scaffold_state_show_bottom_sheet_0.ShowBottomSheetExampleApp(),
'scrollbar_0':(context) => const scrollbar_0.ScrollbarExampleApp(),
'scrollbar_1':(context) => const scrollbar_1.ScrollbarExampleApp(),
'search_anchor_0':(context) => const search_anchor_0.SearchBarApp(),
'search_anchor_1':(context) => const search_anchor_1.PinnedSearchBarApp(),
'search_anchor_2':(context) => const search_anchor_2.SearchBarApp(),
'search_anchor_3':(context) => const search_anchor_3.SearchAnchorAsyncExampleApp(),
'search_anchor_4':(context) => const search_anchor_4.SearchAnchorAsyncExampleApp(),
'search_bar_0':(context) => const search_bar_0.SearchBarApp(),
'segmented_button_0':(context) => const segmented_button_0.SegmentedButtonApp(),
'selectable_region_0':(context) => const selectable_region_0.SelectableRegionExampleApp(),
'selection_area_0':(context) => const selection_area_0.SelectionAreaExampleApp(),
'selection_container_0':(context) => const selection_container_0.SelectionContainerExampleApp(),
'selection_container_disabled_0':(context) => const selection_container_disabled_0.SelectionContainerDisabledExampleApp(),
'slider_0':(context) => const slider_0.SliderApp(),
'slider_1':(context) => const slider_1.SliderApp(),
'slider_2':(context) => const slider_2.SliderApp(),
'snack_bar_0':(context) => const snack_bar_0.SnackBarExampleApp(),
'snack_bar_1':(context) => const snack_bar_1.SnackBarExampleApp(),
'snack_bar_2':(context) => const snack_bar_2.SnackBarExampleApp(),
'stepper_0':(context) => const stepper_0.StepperExampleApp(),
'stepper_controls_builder_0':(context) => const stepper_controls_builder_0.ControlsBuilderExampleApp(),
'switch_0':(context) => const switch_0.SwitchApp(),
'switch_1':(context) => const switch_1.SwitchApp(),
'switch_2':(context) => const switch_2.SwitchApp(),
'switch_3':(context) => const switch_3.SwitchApp(),
'custom_labeled_switch_0':(context) => const custom_labeled_switch_0.LabeledSwitchApp(),
'custom_labeled_switch_1':(context) => const custom_labeled_switch_1.LabeledSwitchApp(),
'switch_list_tile_0':(context) => const switch_list_tile_0.SwitchListTileApp(),
'switch_list_tile_1':(context) => const switch_list_tile_1.SwitchListTileApp(),
'tab_controller_1':(context) => const tab_controller_1.TabControllerExampleApp(),
'tab_bar_0':(context) => const tab_bar_0.TabBarApp(),
'tab_bar_1':(context) => const tab_bar_1.TabBarApp(),
'tab_bar_2':(context) => const tab_bar_2.TabBarApp(),
'text_button_0':(context) => const text_button_0.TextButtonExampleApp(),
'text_button_1':(context) => const text_button_1.Home(),
'text_field_0':(context) => const text_field_0.TextFieldExampleApp(),
'text_field_1':(context) => const text_field_1.TextFieldExampleApp(),
'text_field_2':(context) => const text_field_2.TextFieldExamplesApp(),
'text_form_field_1':(context) => const text_form_field_1.TextFormFieldExampleApp(),
'theme_extension_1':(context) => const theme_extension_1.ThemeExtensionExampleApp(),
'theme_data_0':(context) => const theme_data_0.ThemeDataExampleApp(),
'show_time_picker_0':(context) => const show_time_picker_0.ShowTimePickerApp(),
'toggle_buttons_0':(context) => const toggle_buttons_0.ToggleButtonsExampleApp(),
'toggle_buttons_1':(context) => const toggle_buttons_1.ToggleButtonsApp(),
'tooltip_0':(context) => const tooltip_0.TooltipExampleApp(),
'tooltip_1':(context) => const tooltip_1.TooltipExampleApp(),
'tooltip_2':(context) => const tooltip_2.TooltipExampleApp(),
'tooltip_3':(context) => const tooltip_3.TooltipExampleApp(),
};